[package]
name = "RustRoverProject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conrod = "0.19.0"
gtk = "0.18.1"
iced = "0.2.0"

